# take an input from keyboard and displat it as number
x = int(input("enter anumber: "))
if x==0:print("it is zero")
elif x==1:print("ONE")
elif x==2:print("Two")
elif x==3:print("Three")
elif x==4:print("Four")
elif x==5:print("Five")
elif x==6:print("SIX")
elif x==7:print("SEVEN")
elif x==8:print("Eight")
elif x==9:print("Nine")
elif x==10:print("Ten")
else:print("False input given")