# relational operator
a,b=1,2
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)
print(a==b)
print(a!=b)
n=int(input("enter a number: "))
m=int(input("enter a number: "))
print(m>n)
print(m>=n)
print(m<n)
print(m<=n)
print(m==n)
print(m!=n)